
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Aug 03 11:33:39 CEST 2007
//----------------------------------------------------

package model;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SPHERE = 11;
  public static final int ARRAY_BEGIN = 4;
  public static final int BLOCK_BEGIN = 2;
  public static final int WIDTH = 27;
  public static final int BLOCK_END = 3;
  public static final int MODEL = 7;
  public static final int INTEGER = 38;
  public static final int DOUBLE = 37;
  public static final int CONE = 13;
  public static final int COMPOSITION = 18;
  public static final int TRANSFORMS = 34;
  public static final int DEPTH = 29;
  public static final int TORUS = 10;
  public static final int ARRAY_END = 5;
  public static final int RADIUS = 26;
  public static final int CHILDREN = 33;
  public static final int MOVE_DELTA = 30;
  public static final int CYLINDER = 12;
  public static final int TETRAHEDRON = 15;
  public static final int ANGLE = 25;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int SCALING = 19;
  public static final int COMA = 22;
  public static final int HOME = 23;
  public static final int DISK = 9;
  public static final int TRANSLATION = 17;
  public static final int ROTATION = 16;
  public static final int HEIGHT = 28;
  public static final int TRANSFORMATION_MATRIX = 36;
  public static final int NAME = 6;
  public static final int BOX = 8;
  public static final int COLOR = 24;
  public static final int ADD_CHILDREN = 20;
  public static final int POINT = 35;
  public static final int REMOVE_CHILDREN = 21;
  public static final int SCALE_DELTA = 31;
  public static final int PYRAMID = 14;
  public static final int POLYGONS = 32;
}

